apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-db-seed-v0-3
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: saujandsre/catalog-service:v0.3
          command: ["python", "-m", "app.seed"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef: {name: catalog-db-secret, key: DATABASE_URL}
