apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: saujandsre/order-service:v0.2
          env:
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:8000"

            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service:8000"

            - name: ACCOUNT_SERVICE_URL
              value: "http://account-service:8000"
          ports:
            - containerPort: 8000
