apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: saujandsre/order-service:v0.3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: DATABASE_URL
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:8000"

            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service:8000"

            - name: ACCOUNT_SERVICE_URL
              value: "http://account-service:8000"
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
