apiVersion: batch/v1
kind: Job
metadata:
  name: inventory-db-seed-v0-2
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: saujandsre/inventory-service:v0.2
          command: ["python", "-m", "app.seed"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef: {name: inventory-db-secret, key: DATABASE_URL}
